import JSZip from 'jszip'
import { useFlowStore } from '@/store/flowStore'

// Helper function to download blobs
const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export class BlueprintRegistry {
  static async exportBlueprint() {
    const store = useFlowStore.getState()
    const blueprint = {
      nodes: store.nodes,
      edges: store.edges,
      metadata: {
        version: '2026.2',
        exportedAt: Date.now(),
        author: 'Architect Zero',
      },
    }

    const zip = new JSZip()
    zip.file('blueprint.json', JSON.stringify(blueprint, null, 2))

    // Add separate README
    zip.file('README.md', '# Agent Blueprint\nGenerated by HyperSmol Infinity Store.')

    const content = await zip.generateAsync({ type: 'blob' })
    downloadBlob(content, `agent-blueprint-${Date.now()}.zip`)
  }

  static async importBlueprint(file: File) {
    const zip = await JSZip.loadAsync(file)
    const blueprintFile = zip.file('blueprint.json')

    if (blueprintFile) {
      const content = await blueprintFile.async('string')
      const blueprint = JSON.parse(content)

      // Hydrate store
      useFlowStore.setState({
        nodes: blueprint.nodes,
        edges: blueprint.edges,
      })

      return true
    }
    return false
  }
}
